name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install and test
      run: |
        yarn install --frozen-lockfile
        yarn test
      env:
        CI: true
    - name: Lint
      run: |
        yarn lint
      env:
        CI: true
    - name: Build
      run: |
        yarn build
        touch ./out/.nojekyll
        echo mfr.flavienpensato.ovh > ./out/CNAME
      env:
        CI: true
    - name: Checkout
      uses: actions/checkout@v1
    - name: GitHub Pages Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_PAGES }}
        BRANCH: gh-pages
        FOLDER: out
